# NOMBRE DE LA APLICACIÓN
spring.application.name=cinema-monarca

# PUERTO DINÁMICO (Crucial para Railway)
server.port=${PORT:8080}
server.forward-headers-strategy=native

# PERFIL ACTIVO
spring.profiles.active=prod

# CONEXIÓN A LA BASE DE DATOS
# Se mantiene la URL pública que ya probamos en IntelliJ y funciona
spring.datasource.url=${MYSQL_URL:jdbc:mysql://metro.proxy.rlwy.net:21244/railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:msPDHBYDfRaLulDQMjiAKpfBdBYpierI}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
# Usamos MySQL8Dialect para mejor compatibilidad con Railway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# CONFIGURACIÓN DE SWAGGER / OPENAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# PERMITIR SOBRESCRITURA DE BEANS
spring.main.allow-bean-definition-overriding=true